name: vlfm
channels:
  - conda-forge
  - nodefaults
  - nvidia
  - pytorch
  - pyg
dependencies:
  - python=3.10
  - openssl==3.3.2
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchaudio==2.5.1
  - pytorch-cuda=11.8
  - cuda=11.8
  - cuda-nvcc=11.8
  - cuda-cccl=11.8
  - gxx==9.4.0
  - git==2.47.0
  - git-lfs==3.5.1
  - dash==2.18.1
  - pinocchio==3.3.0
  - harfbuzz==9.0.0
  - pip==24.3.1