"""Spot-style command helpers used by the interactive-search skills API."""

from .frame_helpers import BODY_FRAME_NAME, GRAV_ALIGNED_BODY_FRAME_NAME, ODOM_FRAME_NAME, VISION_FRAME_NAME
from .geometry import EulerZXY
from .robot_command import (
    GripperPositionCommand,
    JointPositionCommand,
    MobilityCommandFeedback,
    MobilityParams,
    RobotCommand,
    RobotCommandBackend,
    RobotCommandBuilder,
    RobotCommandClient,
    RobotCommandFeedback,
    RobotCommandFeedbackResponse,
    RobotCommandFeedbackStatus,
    Se2VelocityCommand,
    SitCommand,
    SitCommandFeedback,
    SitCommandFeedbackStatus,
    StandCommand,
    StandCommandFeedback,
    StandCommandFeedbackStatus,
    SynchronizedCommandFeedback,
    blocking_command,
    blocking_sit,
    blocking_stand,
)
from .sdk import (
    ImageClient,
    ImageResponse,
    ImageSource,
    Lease,
    LeaseClient,
    LeaseKeepAlive,
    LeaseOwner,
    LeaseResourceEntry,
    ManipulationApiClient,
    ManipulationApiFeedbackRequest,
    ManipulationApiFeedbackResponse,
    ManipulationApiResponse,
    ManipulationFeedbackState,
    Robot,
    RobotStateClient,
    Sdk,
    TimeSyncEndpoint,
    TimeSyncThread,
    create_standard_sdk,
    require_image_sources_ready,
    require_robot_state_ready,
)

__all__ = [
    "BODY_FRAME_NAME",
    "GRAV_ALIGNED_BODY_FRAME_NAME",
    "ODOM_FRAME_NAME",
    "VISION_FRAME_NAME",
    "EulerZXY",
    "GripperPositionCommand",
    "ImageClient",
    "ImageResponse",
    "ImageSource",
    "JointPositionCommand",
    "Lease",
    "LeaseClient",
    "LeaseKeepAlive",
    "LeaseOwner",
    "LeaseResourceEntry",
    "ManipulationApiClient",
    "ManipulationApiFeedbackRequest",
    "ManipulationApiFeedbackResponse",
    "ManipulationApiResponse",
    "ManipulationFeedbackState",
    "MobilityCommandFeedback",
    "MobilityParams",
    "Robot",
    "RobotCommand",
    "RobotCommandBackend",
    "RobotCommandBuilder",
    "RobotCommandClient",
    "RobotCommandFeedback",
    "RobotCommandFeedbackResponse",
    "RobotCommandFeedbackStatus",
    "RobotStateClient",
    "Se2VelocityCommand",
    "Sdk",
    "SitCommand",
    "SitCommandFeedback",
    "SitCommandFeedbackStatus",
    "StandCommand",
    "StandCommandFeedback",
    "StandCommandFeedbackStatus",
    "SynchronizedCommandFeedback",
    "TimeSyncEndpoint",
    "TimeSyncThread",
    "blocking_command",
    "blocking_sit",
    "blocking_stand",
    "create_standard_sdk",
    "require_image_sources_ready",
    "require_robot_state_ready",
]

try:
    from .isaaclab_backend import (
        IsaacLabImageBackend,
        IsaacLabManipulationApiBackend,
        IsaacLabRobotCommandBackend,
        IsaacLabRobotStateBackend,
        IsaacLabSpotServiceBinder,
        bind_isaaclab_spot_robot,
    )
except ModuleNotFoundError as exc:
    if exc.name not in {"torch", "isaaclab", "pxr", "omni"}:
        raise
else:
    __all__.extend(
        [
            "IsaacLabImageBackend",
            "IsaacLabManipulationApiBackend",
            "IsaacLabRobotCommandBackend",
            "IsaacLabRobotStateBackend",
            "IsaacLabSpotServiceBinder",
            "bind_isaaclab_spot_robot",
        ]
    )
